version: 2
jobs:
  deploy:
    working_directory: ~/cicd-trial
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $fingerprint
      - run:
          name: Copy File to Server
          command: |
            scp -r ~/cicd-trial/index.html ubuntu@13.229.132.103:/var/www/html
      - run:
          name: Restart Server
          command: |
            ssh ubuntu@13.229.132.103 "sudo service apache2 restart && sudo service apache2 status"
            
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master # only deploy on the master branch
