version: 2
jobs:
  deploy:
    working_directory: ~/cicd-trial
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $fingerprint
      - run:
          name: Deploy Over SSH
          command: |
            scp -r ~/cicd-trial/index.html ubuntu@13.229.132.103:/var/www/html/cicd-trial

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master # only deploy on the master branch
