version: 2
jobs:
  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - $fingerprint
      - run:
          name: Deploy Over SSH
          command: |
            scp -r ~/repo ubuntu@13.229.132.103:/var/www/html/demo

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master # only deploy on the master branch
